### ISSUE TITLE
OPS TODO Task List

### ISSUE THREAD

**Issue by gihanmudalige** [OP-DSL/OPS#157]
Task List for OPS Release 
- [ ] OPS Move code generated APPS to OPS-APPS repo - automatically regenerate code for changes in OP2-Common repo
- [ ] Add AMD HIP tests to CI test flow

Task list for next Release
- [ ]  OPS build with SPACK recipies / config 
- [ ]  Upgrade/Update OPS code generator to use OP-CG codegen ideas - see  https://github.com/jdjfisher/op-cg
- [ ]  Add SYCL Parallelization to OPS repo
- [ ]  OPS Fortran API develop - more applications, updated code generator (in line with C/C++ API/build)
- [ ]  Test / Add to CI tests the Tridsolver integration testing on non-intel CPUs
- [ ]  Add to readthedocs documentation - Dev-Docs and other missing sections

**Comment by gihanmudalige** [comment]
**Updated currently outstanding issues **
- [x] Poisson (and some other) Fortran apps with + Tiling have runtime error, needs fixing
- [x] Fix for lowdim broadcasting issue
- [ ] OPS CI/CD additions including new cmake file and adding Fortran apps to CI
- [x] ifx cannot target nvidia gpu need to use C compiler for linking when building f2c_sycl with Intel compilers
- [ ] JIT compilation with F2C translation
- [ ] Fix Tiling bug affecting validation for some apps
- [ ] Tiling with multiple blocks
- [ ] Update  the multiple Check pointing API calls with cleaner single ops_checkpoint(...) API
